Repository samvera-labs/avalon-bundle, pull requests merged in 2018-03, with the labels that each got.

#7 Configure code climate
  .codeclimate.yml
  .rubocop.cc.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  app/models/ability.rb
  app/models/search_builder.rb
  app/models/solr_document.rb
  app/models/user.rb
  bin/jetty_wait
  circle.yml
  karma.conf.js
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/fixtures/users.yml
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/models/user_test.rb
  test/system/.keep
  test/test_helper.rb
Labels: in progress

#9 Fix configurations
  Gemfile
  Gemfile.lock
  config/fedora.yml
  config/initializers/config.rb
  config/redis.yml
  config/settings.yml
  config/solr.yml
  docker-compose.yml
Labels: In Review

#10 Add archivist1@example.com to admin role in developement
  config/role_map.yml
Labels: In Review

#11 Upgrade to Hyrax 2.1.0.beta1
  .rubocop.cc.yml
  .rubocop.yml
  .rubocop_fixme.yml
  Gemfile
  Gemfile.lock
  app/actors/hyrax/actors/generic_work_actor.rb
  app/controllers/hyrax/generic_works_controller.rb
  app/forms/hyrax/generic_work_form.rb
  app/indexers/generic_work_indexer.rb
  app/models/generic_work.rb
  app/presenters/hyrax/generic_work_presenter.rb
  app/views/hyrax/generic_works/_generic_work.html.erb
  config/initializers/hyrax.rb
  config/locales/generic_work.de.yml
  config/locales/generic_work.en.yml
  config/locales/generic_work.es.yml
  config/locales/generic_work.fr.yml
  config/locales/generic_work.it.yml
  config/locales/generic_work.pt-BR.yml
  config/locales/generic_work.zh.yml
  db/migrate/20180302041012_create_collection_types.hyrax.rb
  db/migrate/20180302041013_update_collection_type_column_names.hyrax.rb
  db/migrate/20180302041014_update_collection_type_column_options.hyrax.rb
  db/migrate/20180302041015_create_collection_branding_infos.hyrax.rb
  db/migrate/20180302041016_create_collection_type_participants.hyrax.rb
  db/migrate/20180302041017_rename_admin_set_id_to_source_id.hyrax.rb
  db/migrate/20180302041018_add_collection_type_sharing_options.hyrax.rb
  db/schema.rb
  spec/actors/hyrax/actors/generic_work_actor_spec.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/features/create_generic_work_spec.rb
  spec/forms/hyrax/generic_work_form_spec.rb
  spec/models/generic_work_spec.rb
  spec/presenters/hyrax/generic_work_presenter_spec.rb
Labels: In Review

#13 Enable ffmpeg
  config/initializers/hyrax.rb
Labels: In Review

#14 Add xray-rails in development for easily identifying view partials
  Gemfile
  Gemfile.lock
Labels: In Review

#16 Enable UV viewer for images
  Gemfile
  Gemfile.lock
  app/assets/images/us_404.svg
  config/environments/development.rb
  config/initializers/hyrax.rb
  config/initializers/riiif.rb
  config/routes.rb
Labels: In Review

#15 Add MediaelementJS source pack files, plus a hardcoded video to gener…
  .gitignore
  app/javascript/packs/avalon-iiif-pack.js
  app/javascript/packs/avalon-iiif/index.js
  app/javascript/packs/avalon-player-pack.js
  app/javascript/packs/avalon-player/index.js
  app/javascript/packs/avalon-player/lunchroom-manners-manifest.json
  app/javascript/packs/avalon-player/styles/avalon-bundle-styles.css
  app/views/hyrax/base/_representative_media.html.erb
  package.json
  yarn.lock
Labels: In Review

#19 Fix some webpacker compile errors due to ESLint complaints and unneed…
  app/javascript/packs/avalon-iiif-pack.js
  app/javascript/packs/avalon-iiif/index.js
  app/javascript/packs/avalon-player/index.js
Labels: In Review

#20 Update nodejs version
  circle.yml
Labels: In Review

#17 Allow generic work presenter to choose between UV and avalon iiif viewer
  .rubocop_fixme.yml
  Gemfile
  app/helpers/generic_work_helper.rb
  app/presenters/hyrax/generic_work_presenter.rb
  app/views/hyrax/base/_representative_media.html.erb
  app/views/hyrax/base/iiif_viewers/_avalon.html.erb
  app/views/hyrax/base/iiif_viewers/_universal_viewer.html.erb
  app/views/hyrax/base/show.html.erb
  spec/helpers/generic_work_helper_spec.rb
  spec/presenters/hyrax/generic_work_presenter_spec.rb
Labels: In Review

#21 Fix REDIS_PORT env var
  config/redis.yml
Labels: In Review

#12 Use CircleCI 2.0
  .circleci/config.yml
  .codeclimate.yml
  circle.yml
  docker-compose.yml
  karma.conf.js
  spec/features/create_generic_work_spec.rb
Labels: In Review, sprint 148

#23 Add Capistrano for automating deploys
  Capfile
  Gemfile
  Gemfile.lock
  README.md
  config/deploy.rb
  config/deploy/docker.rb
  db/schema.rb
  docker-compose.yml
Labels: In Review

#22 Update to play video source file instead of placeholder
  .gitignore
  app/javascript/packs/avalon-player/index.js
  app/javascript/packs/avalon-player/styles/avalon-bundle-styles.css
  app/views/hyrax/base/iiif_viewers/_avalon.html.erb
Labels: In Review
